version: '3.8'

services:
  web:
      build: .
      container_name: lamp_php
      ports:
        - "8090:80"
      volumes:
        - ../code:/var/www/html
        - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

  db:
    image: mysql:5.7
    container_name: lamp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myDB
      MYSQL_USER: userdb
      MYSQL_PASSWORD: passdb
    volumes:
      - db_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8091:80"

volumes:
  db_data: